{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-allcontributors
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/allcontributors_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/allcontributors/allcontributors_{{ version }}.tar.gz
  sha256: c39933acf59c748e4b58fe30aea19fa3946731fbe931049c13c6a6370639b37b

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-clipr
    - r-curl
    - r-gert
    - r-gh
    - r-gitcreds
    - r-httr2
    - r-magrittr
  run:
    - r-base
    - r-cli
    - r-clipr
    - r-curl
    - r-gert
    - r-gh
    - r-gitcreds
    - r-httr2
    - r-magrittr

test:
  commands:
    - $R -e "library('allcontributors')"           # [not win]
    - "\"%R%\" -e \"library('allcontributors')\""  # [win]

about:
  home: https://github.com/ropenscilabs/allcontributors
  doc_url: https://docs.ropensci.org/allcontributors/
  license: GPL-3.0-only
  summary: Acknowledge all contributors to a project via a single function call. The function appends to a 'README' or other specified file(s) a table with names of all individuals who contributed via code or repository issues.  The package also includes several additional functions to extract and quantify contributions
    to any repository.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: allcontributors
# Title: Acknowledge all Contributors to a Project
# Version: 0.1.1
# Authors@R: person("Mark", "Padgham", , "mark.padgham@email.com", role = c("aut", "cre"))
# Description: Acknowledge all contributors to a project via a single function call. The function appends to a 'README' or other specified file(s) a table with names of all individuals who contributed via code or repository issues.  The package also includes several additional functions to extract and quantify contributions to any repository.
# License: GPL-3
# URL: https://github.com/ropenscilabs/allcontributors
# BugReports: https://github.com/ropenscilabs/allcontributors/issues
# Imports: cli, clipr, curl, gert, gh, gitcreds, httr2, magrittr
# Suggests: httptest2, knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-GB
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-10-06 10:03:32 UTC; smexus
# Author: Mark Padgham [aut, cre]
# Maintainer: Mark Padgham <mark.padgham@email.com>
# Repository: CRAN
# Date/Publication: 2023-10-06 14:30:16 UTC
